# Generated by Django 5.2.7 on 2025-10-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_identificacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('Tipo_movimiento', models.CharField(choices=[('I', 'Ingreso'), ('R', 'Retiro')], default='Ingreso', max_length=2)),
            ],
        ),
    ]
