# Generated by Django 5.2.7 on 2025-10-07 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_movimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientos',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to=settings.AUTH_USER_MODEL),
        ),
    ]
