# Generated by Django 5.2.7 on 2025-10-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_movimientos_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empresa', 'Empresa'), ('empleado', 'Empleado')], default='Empresa', max_length=20),
        ),
    ]
